services:
  mysql:
    image: mysql:8.0
    container_name: bugs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bugsdb
      MYSQL_USER: bugsuser
      MYSQL_PASSWORD: bugspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  bugs-app:
    build: .
    container_name: bugs-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bugsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bugsuser
      SPRING_DATASOURCE_PASSWORD: bugspassword
    depends_on:
      - mysql

volumes:
  mysql_data: